### PR TITLE
update struct validations to validator.v10

### PR DESCRIPTION
**Pull request by verymiao**
gopkg.in/go-playground/validator.v8 is older version, so update version to github.com/go-playground/validator/v10

### CODE REVIEW

**Review by thinkerou — APPROVED** [review]
lgtm

**Comment by zqwalker** [comment]
I believe this example is incorrect. UserStructLevelValidation should only take one argument of the type validator.StructLevel

**Comment by verymiao** [comment]
> 我相信这个例子是不正确的。UserStructLevelValidation 应该只接受一个类型为 validator.StructLevel 的参数

thx, I'll verify this on Monday. this example run well on my mac.

**Comment by verymiao** [comment]
> I believe this example is incorrect. UserStructLevelValidation should only take one argument of the type validator.StructLevel

I fix it, #62

**Pull request merged**
